global:
  scrape_interval: 1m

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: postgres
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: mysql
    static_configs:
      - targets: ["mysqld_exporter:9104"]

  - job_name: redis
    static_configs:
      - targets: ["redis_exporter:9121"]
