services:
  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - minio
    volumes:
      - minio-data:/data
    command:
      ["server", "/data", "--address", ":9000", "console-address", ":9001"]

volumes:
  minio-data:

networks:
  minio:
    external: true
