services:
  mysql:
    image: mysql:8.3
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql
    command: ["mysqld", "--mysql-native-password=ON"]

networks:
  mysql:
    external: true

volumes:
  mysql-data:
