services:
  mysql:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql
    command: mysqld --default-authentication-plugin=mysql_native_password

networks:
  mysql:
    external: true

volumes:
  mysql-data:
