services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ['postgres', '-c', 'wal_level=logical']
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres

networks:
  postgres:
    external: true

volumes:
  postgres-data:
