pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/hothienlac/server'
            }
        }

        stage('Run Docker Compose') {
            steps {
                script {
                    dir('jenkins-deploy/authelia') {
                        sh 'docker-compose up -d'
                    }
                }
            }
        }
    }
}
