services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    restart: unless-stopped
    networks:
      - clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/log/clickhouse-server
    environment:
      CLICKHOUSE_DB: app
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  clickhouse-client:
    image: clickhouse/clickhouse-client:latest
    restart: unless-stopped
    networks:
      - clickhouse
    depends_on:
      - clickhouse-server
    entrypoint: >
      bash -c "until clickhouse-client --host clickhouse-server --user admin --password secret123 --query='SELECT 1'; do sleep 1; done && tail -f /dev/null"

networks:
  clickhouse:
    external: true

volumes:
  clickhouse_data:
  clickhouse_logs:
