services:
  cert-generator:
    image: ubuntu:latest
    container_name: cert-generator
    command: >
      sh -c "openssl req -x509 -nodes -days 3650 -newkey rsa:4096 \
             -keyout /certs/dragonfly.key -out /certs/dragonfly.crt \
             -subj '/C=US/ST=State/L=City/O=Organization/CN=dragonfly.local'"
    volumes:
      - dragonfly_certs:/certs

  dragonflydb:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly:latest'
    container_name: dragonflydb
    restart: always
    # depends_on:
    #   cert-generator:
    #     condition: service_completed_successfully
    ports:
      - '6378:6379'
    volumes:
      - dragonfly-data:/data
      - dragonfly_certs:/tls:ro
    command:
      - "--requirepass=${DRAGONFLY_PASSWORD}"
      - "--tls"
      - "--tls_cert_file=/tls/dragonfly.crt"
      - "--tls_key_file=/tls/dragonfly.key"
      - "--maxmemory=1gb"
      - "--dir=/data"
      - "--save_schedule=*:60"
    environment:
      DRAGONFLY_PASSWORD: ${DRAGONFLY_PASSWORD}

volumes:
  dragonfly-data:
  dragonfly_certs:
