services:
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    networks:
      - grafana
      - nginx-proxy-manager
      - influxdb
      - postgres
      - mysql
      - prometheus
      - loki
      - tempo
      - otel


volumes:
  grafana_data:

networks:
  grafana:
    external: true
  nginx-proxy-manager:
    external: true
  influxdb:
    external: true
  postgres:
    external: true
  mysql:
    external: true
  prometheus:
    external: true
  loki:
    external: true
  tempo:
    external: true
  otel:
    external: true

