services:
  huynhxuanyen:
    image: wordpress
    restart: unless-stopped
    ports:
      - 18001:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
    volumes:
      - huynhxuanyen_data:/var/www/html
    networks:
      - huynhxuanyen
      - mysql
      - nginx-proxy-manager

volumes:
  huynhxuanyen_data:

networks:
  huynhxuanyen:
    external: true
  mysql:
    external: true
  nginx-proxy-manager:
    external: true
