services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    privileged: true
    ports:
      - 18081:8080
    networks:
      - jenkins
      - nginx-proxy-manager
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

networks:
  jenkins:
    external: true
  nginx-proxy-manager:
    external: true

volumes:
  jenkins_home:
