services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    ports:
      - 8082:8080
    networks:
      - keycloak
      - postgres
      - nginx-proxy-manager
    environment:
      KC_HOSTNAME: keycloak.hothienlac.com
      KC_HOSTNAME_PORT: 8080
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true

      KEYCLOAK_ADMIN: $KEYCLOAK_ADMIN
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    command: start

networks:
  keycloak:
    external: true
  postgres:
    external: true
  nginx-proxy-manager:
    external: true
