services:
  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - minio
      - nginx-proxy-manager
    volumes:
      - minio-data:/data
    command:
      ["server", "/data", "--address", ":9000", "--console-address", ":9001"]

volumes:
  minio-data:

networks:
  minio:
    external: true
  nginx-proxy-manager:
    external: true
