services:
  mysql:
    image: mysql:9.3
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql

  mysqld_exporter:
    image: prom/mysqld-exporter
    networks:
      - prometheus
      - mysql
    environment:
      DATA_SOURCE_NAME: ${DATA_SOURCE_NAME}
    depends_on:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    external: true
  prometheus:
    external: true

volumes:
  mysql-data:
