services:
  nextcloud:
    image: nextcloud
    restart: unless-stopped
    networks:
      - nextcloud
      - postgres
      - redis
      - minio
      - nginx-proxy-manager
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      REDIS_HOST: redis
      REDIS_PORT: 6379


networks:
  nextcloud:
    external: true
  postgres:
    external: true
  redis:
    external: true
  minio:
    external: true
  nginx-proxy-manager:
    external: true
