services:
  nextcloud:
    image: nextcloud
    restart: unless-stopped
    ports:
      - 18888:80
    networks:
      - nextcloud
      - postgres
      - redis
      - minio
      - nginx-proxy-manager
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OBJECTSTORE_S3_BUCKET: nextcloud
      OBJECTSTORE_S3_HOST: http://minio
      OBJECTSTORE_S3_PORT: 9000
      OBJECTSTORE_S3_KEY: $OBJECTSTORE_S3_KEY
      OBJECTSTORE_S3_SECRET: $OBJECTSTORE_S3_SECRET


networks:
  nextcloud:
    external: true
  postgres:
    external: true
  redis:
    external: true
  minio:
    external: true
  nginx-proxy-manager:
    external: true
