services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ['postgres', '-c', 'wal_level=logical']
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    networks:
      - prometheus
      - postgres
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/?sslmode=disable"
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    external: true
  prometheus:
    external: true

volumes:
  postgres-data:
