services:
  prometheus:
    image: registry.hothienlac.com/prometheus:latest
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
    networks:
      - prometheus

volumes:
  prometheus_data:

networks:
  prometheus:
    external: true
