services:
  redis:
    image: redis/redis-stack
    restart: unless-stopped
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - redis
    volumes:
      - redis-data:/data

  redis_exporter:
    image: oliver006/redis_exporter:v1.61.0
    networks:
      - redis
      - prometheus
    environment:
      REDIS_ADDR: "redis://redis:6379"
    depends_on:
      - redis
    restart: unless-stopped

networks:
  redis:
    external: true
  prometheus:
    external: true

volumes:
  redis-data:
