services:
  registry:
    image: registry:2
    restart: unless-stopped
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: "['*']"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: "['GET', 'DELETE', 'OPTIONS']"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: "['Authorization', 'Accept']"
    volumes:
      - registry-data:/var/lib/registry
      - auth:/auth
    networks:
      - registry
      - nginx-proxy-manager
    depends_on:
      - htpasswd

  htpasswd:
    image: httpd:2.4
    entrypoint: >
      bash -c "
      htpasswd -Bbc /auth/htpasswd \"$REGISTRY_USER\" \"$REGISTRY_PASS\"
      "
    environment:
      REGISTRY_USER: ${REGISTRY_USER}
      REGISTRY_PASS: ${REGISTRY_PASS}
    volumes:
      - auth:/auth

networks:
  registry:
    external: true
  nginx-proxy-manager:
    external: true

volumes:
  registry-data:
  auth:
