services:
  wordpress:
    image: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress
      - mysql
      - nginx-proxy-manager

volumes:
  wordpress_data:

networks:
  wordpress:
    external: true
  mysql:
    external: true
  nginx-proxy-manager:
    external: true
