services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - confluent
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log

networks:
  confluent:
    external: true

volumes:
  zookeeper-data:
  zookeeper-logs:
